Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 5
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	6	BamIndex
	3	Bwa
	2	GATKBQSR
	2	GATKBQSRPre
	2	GATKLeftAlign
	2	GATKReAlign
	2	GATKReAlignPre
	2	MarkDupWithPicard
	2	MergeBam
	1	all
	3	fastp
	3	fastqc
	3	fastqc2
	3	loadrawData
	1	multiqc
	37

[Sat Jun 27 17:53:58 2020]
rule loadrawData:
    input: /home/DATA/NA12878/pipelineTest/fastq/HG001_1000G_chr20_1.fq, /home/DATA/NA12878/pipelineTest/fastq/HG001_1000G_chr20_2.fq
    output: ../../ngs_test_data/rawdata/HG001/N1/HG001_N1_L1_1.fq.gz, ../../ngs_test_data/rawdata/HG001/N1/HG001_N1_L1_2.fq.gz
    jobid: 16
    wildcards: case=HG001, sample=N1, unit=L1
    threads: 4

[Sat Jun 27 17:54:00 2020]
Error in rule loadrawData:
    jobid: 16
    output: ../../ngs_test_data/rawdata/HG001/N1/HG001_N1_L1_1.fq.gz, ../../ngs_test_data/rawdata/HG001/N1/HG001_N1_L1_2.fq.gz

RuleException:
CalledProcessError in line 12 of /home/pengjia/ProjectSnake/DNAseq/dna/smk/qc.smk:
Command 'set -euo pipefail;  /home/pengjia/miniconda3/envs/smk/bin/python3.6 /home/pengjia/ProjectSnake/DNAseq/dna/.snakemake/scripts/tmpd04rn44k.wrapper.py' returned non-zero exit status 1.
  File "/home/pengjia/ProjectSnake/DNAseq/dna/smk/qc.smk", line 12, in __rule_loadrawData
  File "/home/pengjia/miniconda3/envs/smk/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Job failed, going on with independent jobs.

[Sat Jun 27 17:54:00 2020]
rule loadrawData:
    input: /home/DATA/NA12878/pipelineTest/fastq/HG001_GIAB_chr20_1.fq, /home/DATA/NA12878/pipelineTest/fastq/HG001_1000G_chr20_2.fq
    output: ../../ngs_test_data/rawdata/HG001/N/HG001_N_L1_1.fq.gz, ../../ngs_test_data/rawdata/HG001/N/HG001_N_L1_2.fq.gz
    jobid: 15
    wildcards: case=HG001, sample=N, unit=L1
    threads: 4

[Sat Jun 27 17:54:01 2020]
Error in rule loadrawData:
    jobid: 15
    output: ../../ngs_test_data/rawdata/HG001/N/HG001_N_L1_1.fq.gz, ../../ngs_test_data/rawdata/HG001/N/HG001_N_L1_2.fq.gz

RuleException:
CalledProcessError in line 12 of /home/pengjia/ProjectSnake/DNAseq/dna/smk/qc.smk:
Command 'set -euo pipefail;  /home/pengjia/miniconda3/envs/smk/bin/python3.6 /home/pengjia/ProjectSnake/DNAseq/dna/.snakemake/scripts/tmplpu8rdgu.wrapper.py' returned non-zero exit status 1.
  File "/home/pengjia/ProjectSnake/DNAseq/dna/smk/qc.smk", line 12, in __rule_loadrawData
  File "/home/pengjia/miniconda3/envs/smk/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Job failed, going on with independent jobs.

[Sat Jun 27 17:54:02 2020]
rule loadrawData:
    input: /home/DATA/NA12878/pipelineTest/fastq/HG001_1000GDeep_chr20_1.fq.gz, /home/DATA/NA12878/pipelineTest/fastq/HG001_1000GDeep_chr20_2.fq.gz
    output: ../../ngs_test_data/rawdata/HG001/N1/HG001_N1_L2_1.fq.gz, ../../ngs_test_data/rawdata/HG001/N1/HG001_N1_L2_2.fq.gz
    jobid: 17
    wildcards: case=HG001, sample=N1, unit=L2
    threads: 4

[Sat Jun 27 17:54:03 2020]
Error in rule loadrawData:
    jobid: 17
    output: ../../ngs_test_data/rawdata/HG001/N1/HG001_N1_L2_1.fq.gz, ../../ngs_test_data/rawdata/HG001/N1/HG001_N1_L2_2.fq.gz

RuleException:
CalledProcessError in line 12 of /home/pengjia/ProjectSnake/DNAseq/dna/smk/qc.smk:
Command 'set -euo pipefail;  /home/pengjia/miniconda3/envs/smk/bin/python3.6 /home/pengjia/ProjectSnake/DNAseq/dna/.snakemake/scripts/tmprndwff40.wrapper.py' returned non-zero exit status 1.
  File "/home/pengjia/ProjectSnake/DNAseq/dna/smk/qc.smk", line 12, in __rule_loadrawData
  File "/home/pengjia/miniconda3/envs/smk/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
Complete log: /home/pengjia/ProjectSnake/DNAseq/dna/.snakemake/log/2020-06-27T175355.162999.snakemake.log
